# Site settings
title: lZackx
motto: I am the Will of my Codes
email: zackx@foxmail.com
description: > # this means to ignore newlines until "baseurl:"
  A Full Stack Developer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lzackx.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  lzackx

# Build settings
markdown: kramdown
